---

  - hosts: all
    user: root
    tasks:

      - name: Install prerequisites in Fedora 21
        yum: >
          name={{ item }}
          state=present
        with_items:
          - deltarpm
          - dnf
          - dnf-automatic
          - htop
          - grub2
          - grubby
          - yum-plugin-fastestmirror
          - yum-utils

      - name: Ensure extlinux and cloud-init are removed
        dnf:
          name: "{{ item }}"
          state: absent
        with_items:
          - cloud-init
          - syslinux-extlinux

      - name: Check to see if grub has been configured
        stat: path=/boot/grub2/grub.cfg
        register: grub_config

      - name: Write grub configuration file
        command: grub2-mkconfig -o /boot/grub2/grub.cfg
        when: grub_config.stat.exists == False

      - name: Write grub to MBR
        command: grub2-install /dev/xvda
        when: grub_config.stat.exists == False

      - name: Remove /boot/extlinux.conf
        file:
          dest: /boot/extlinux.conf
          state: absent

      - name: Ensure Fedora 21 system is fully up to date
        command: dnf -y upgrade

      - name: Upgrade to Fedora 22
        command: dnf distro-sync --releasever=22 --assumeyes

      - name: Relabel SELinux contexts on reboot (requires an extra reboot)
        file: >
          dest=/.autorelabel
          state=touch

      - name: Configure automated updates
        lineinfile:
          dest: /etc/dnf/dnf-automatic.conf
          regexp: "^apply_updates"
          line: "apply_updates = yes"
          state: present

      - name: Enable automatic updates
        service:
          name: dnf-automatic.timer
          enabled: yes
          state: started

      - name: Reboot server
        command: shutdown -r now "Ansible requesting reboot"
        async: 0
        poll: 0
        ignore_errors: true

      - name: Waiting for server to come back (two reboots pending)
        local_action: >
          wait_for
          host={{ inventory_hostname }}
          port=22
          state=started

      - name: Refreshing facts
        action: setup

      - name: Checking for success...
        debug: msg="Something went wrong during the upgrade.  Your server is still on Fedora 21."
        when: ansible_distribution_major_version == "21"

      - name: Success!
        debug: var=ansible_distribution_release
        when: ansible_distribution_major_version == "22"
